### ISSUE TITLE
Konfigurasi database pada server menggunakan docker

### ISSUE THREAD

**Issue by muhammadrifal** [ProgrammerZamanNow/qna#825]
Kang mau tanya, kalau misal aplikasi saya menggunakan laravel dan mysql sebagai database pada satu container dengan docker. Saat development di local tentu saja tidak masalah. Namun ketika di production sebaiknya apakah tetap satu container saja antara aplikasi dan database ? atau sebaiknya yang di container hanya aplikasinya saja ? tetapi database tetap install langsung di server agar mudah konfigurasi untuk backup, cloning database dan sebagainya.
terima kasih

**Comment by youyoumu** [comment]
kalau menurut saya lebih baik setiap aplikasi dan database punya containernya masin-masing. bahkan tidak ada salahnya pakai database yang jalan di docker saat development.

saya pribadi kalau install posgress lebih suka pakai docker karena lebih simpel.
pertama buat `compose.yaml`
```
services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_passwoord
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
```
lalu tinggal `docker compose up`
